import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Providers from './providers';

const sfPro = localFont({
  src: [
    {
      path: '../public/fonts/sf-pro-display-regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/sf-pro-display-semibold.woff2',
      weight: '600',
      style: 'normal',
    },
  ],
  variable: '--font-sfpro',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${sfPro.variable} h-full antialiased`}>
      <body className="container mx-auto font-sans min-h-screen">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
